name: Build APK package

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Signing key
        run: |
          echo "$APK_SIGNING_SECRET" >> /tmp/signing-secret.priv 
        env:
          APK_SIGNING_SECRET: ${{secrets.APK_SIGNING_SECRET}}
      - name: Install Melange
        run: /home/linuxbrew/.linuxbrew/bin/brew install melange
      - name: Build package
        run: /home/linuxbrew/.linuxbrew/bin/melange build --signing-key=/tmp/signing-secret.priv --runner=docker melange.yaml
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: studio-cli-apk-package
          path: ./packages
